//! The `com.nilfactor.Clippo` D-Bus surface, defined exactly once.
//!
//! Three binaries speak this interface — `clippod` serves it, `clippo` and
//! `clippo-applet` call it — and D-Bus checks signatures at *runtime*. A
//! parameter that drifts from `u` to `x` in one crate and not the others is an
//! `org.freedesktop.DBus.Error.InvalidArgs` at the moment a user clicks
//! something, with nothing at compile time to warn anybody. So neither side
//! restates the signatures:
//!
//! - [`ClippoInterface`] is the served side, `#[zbus::interface]` and all. It
//!   holds no state of its own; it forwards to a [`ClippoBackend`], which is
//!   the trait `clippod` implements.
//! - [`ClippoProxy`] is the calling side, generated by `#[zbus::proxy]` from
//!   the same member list.
//!
//! Changing a signature therefore means changing it here, and every crate that
//! disagrees stops compiling.
//!
//! # The members
//!
//! DESIGN.md's table, verbatim — see `clippod` there:
//!
//! | Member | Signature |
//! |---|---|
//! | `List` | `(limit, offset) -> Vec<EntrySummary>` |
//! | `Search` | `(query, limit) -> Vec<EntrySummary>` |
//! | `Copy` / `Delete` | `(id)` |
//! | `Pin` | `(id, bool)` |
//! | `Clear` | `(include_pinned)` |
//! | `Reveal` | `(id) -> String` |
//! | `Thumbnail` | `(id) -> Vec<u8>` |
//! | `SetPaused` / `Paused` | `(bool)` / `-> bool` |
//! | `HistoryChanged` | signal |
//!
//! `Thumbnail` is the one member DESIGN.md's table does not list, added at M5.
//! Its absence was a gap rather than a decision: the design has capture derive
//! and store a thumbnail expressly "so the applet never decodes full-size
//! images", and without a member to fetch one the applet could only have got
//! there through the full-size blob — the thing the thumbnail exists to avoid.
//! It returns derived bytes, not stored content, so it does not widen what
//! [`Reveal`][ClippoBackend::reveal] is the sole route for.
//!
//! # The other direction
//!
//! [`AppletInterface`] and [`ClippoAppletProxy`] are a second, much smaller
//! interface that the *applet* serves and `clippo show` calls. See
//! [`applet`](crate::applet) for why it is a separate bus name.
//!
//! # Previews and full values
//!
//! [`EntrySummary::preview`] is the *only* content [`List`][ClippoBackend::list]
//! and [`Search`][ClippoBackend::search] return, and
//! [`Reveal`][ClippoBackend::reveal] is the only member that returns a whole
//! stored value. That split is load bearing: M4 makes previews of suspected
//! secrets masked, and it does so by changing the one function that builds a
//! preview. If a full value could leave by any other route, M4 would be a
//! redesign instead of an edit.
//!
//! ```no_run
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let connection = zbus::Connection::session().await?;
//! let clippo = clippo_ipc::ClippoProxy::new(&connection).await?;
//! for entry in clippo.list(10, 0).await? {
//!     println!("{}\t{}", entry.id, entry.preview);
//! }
//! # Ok(())
//! # }
//! ```

mod applet;
mod proxy;
mod service;

use serde::{Deserialize, Serialize};
use zbus::zvariant::Type;

pub use applet::{
    AppletFrontend, AppletInterface, ClippoAppletProxy, ClippoAppletProxyBlocking, APPLET_BUS_NAME,
    APPLET_INTERFACE_NAME, APPLET_OBJECT_PATH,
};
pub use proxy::{ClippoProxy, ClippoProxyBlocking};
pub use service::{emitter, ClippoBackend, ClippoInterface};

/// Well-known bus name of the clippo daemon.
pub const BUS_NAME: &str = "com.nilfactor.Clippo";

/// Object path the daemon exports its interface on.
pub const OBJECT_PATH: &str = "/com/nilfactor/Clippo";

/// Name of the interface itself, which happens to equal [`BUS_NAME`].
///
/// Spelled out separately because the two are different things that are only
/// incidentally the same string: one names a process on the bus, the other
/// names a set of members.
pub const INTERFACE_NAME: &str = "com.nilfactor.Clippo";

/// The D-Bus error names that mean "nobody is serving that name".
///
/// `ServiceUnknown` is what a call to an unowned, non-activatable name gets;
/// `NameHasNoOwner` is what the bus says when asked about the name directly.
/// Both mean the same thing to a caller.
const ABSENT_SERVICE: [&str; 2] = [
    "org.freedesktop.DBus.Error.ServiceUnknown",
    "org.freedesktop.DBus.Error.NameHasNoOwner",
];

/// Whether a failed call means "nothing is serving this name" rather than "the
/// service said no".
///
/// Here rather than in each caller because both frontends have to tell those
/// apart and both would otherwise carry their own copy of the two names: the
/// CLI turns one into `clippod is not running` and the applet into its explicit
/// no-daemon state, and a name added in one copy and not the other is a
/// frontend that reports a dead daemon as a refusal. This crate already exists
/// to hold the one definition both sides share.
pub fn is_service_absent(error: &zbus::Error) -> bool {
    error_name(error).is_some_and(|name| ABSENT_SERVICE.contains(&name.as_str()))
}

/// The D-Bus error name of a failed call, when it has one.
///
/// Not every [`zbus::Error`] is an error *reply* — a transport failure has no
/// name at all — which is why this is an `Option` rather than a string that
/// would sometimes be empty.
pub fn error_name(error: &zbus::Error) -> Option<String> {
    use zbus::DBusError as _;

    match error {
        zbus::Error::MethodError(name, _, _) => Some(name.as_str().to_owned()),
        zbus::Error::FDO(error) => Some(error.name().as_str().to_owned()),
        _ => None,
    }
}

/// One history entry as the frontends see it: enough to draw a row, and no
/// clipboard content beyond the preview.
///
/// Deliberately not [`clippo_core::Entry`]. That type carries `hash`, which is
/// an unsalted BLAKE3 of the copied bytes and therefore a confirmation oracle
/// for a guessed value — it belongs inside the encrypted database, not on a
/// session bus that any process running as the user can call. This type is what
/// is safe to hand out.
///
/// The D-Bus signature is `(xxxssbb)`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
pub struct EntrySummary {
    /// The entry's id, as passed back to `Copy`, `Delete`, `Pin` and `Reveal`.
    pub id: i64,
    /// When the copy was first captured, in Unix milliseconds.
    pub created_at: i64,
    /// When it was last copied or pasted, in Unix milliseconds. This is what
    /// [`ClippoBackend::list`] orders by, newest first.
    pub last_used_at: i64,
    /// The [`clippo_core::EntryKind`] word: `text`, `html`, `uris` or `image`.
    pub kind: String,
    /// A short, single-line rendering of the content — `ab••••••••yz` when the
    /// entry is [`sensitive`](Self::sensitive). Never the whole value; that is
    /// `Reveal`'s job alone.
    ///
    /// The masking happened at capture: this field is `entries.preview`, which
    /// is already a mask in the database for a sensitive entry. There is no
    /// unmasked preview for a `List` or a `Search` to return.
    ///
    /// With one bounded exception, worth naming because it is the first
    /// database anyone runs this against: rows captured before masking existed
    /// keep the preview they were stored with, since there is no migration pass
    /// over the history. Copying such a value again re-detects it and replaces
    /// the preview with a mask, so the exception shrinks with use and covers
    /// nothing the user has touched since.
    pub preview: String,
    /// Whether the entry is exempt from retention and from an ordinary
    /// `Clear`.
    pub pinned: bool,
    /// Whether clippo suspects this is a password or a token. Frontends render
    /// a lock badge on these rows.
    pub sensitive: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn object_path_matches_bus_name() {
        assert_eq!(OBJECT_PATH, format!("/{}", BUS_NAME.replace('.', "/")));
    }

    /// The wire signature is what a mismatched frontend actually trips over, so
    /// it is pinned here rather than left to whatever the field order happens
    /// to be after the next edit.
    #[test]
    fn the_entry_summary_signature_is_the_one_frontends_expect() {
        assert_eq!(EntrySummary::SIGNATURE.to_string(), "(xxxssbb)");
    }

    /// `Reveal` returns the whole value; nothing else does. Stated as a test so
    /// that adding a full-value field to this type has to argue with M4 first.
    #[test]
    fn an_entry_summary_carries_no_flavor_data_or_hash() {
        let summary = EntrySummary {
            id: 1,
            created_at: 0,
            last_used_at: 0,
            kind: "text".to_owned(),
            preview: "hu\u{2026}".to_owned(),
            pinned: false,
            sensitive: true,
        };
        let rendered = format!("{summary:?}");
        assert!(!rendered.contains("data"), "{rendered}");
        assert!(!rendered.contains("hash"), "{rendered}");
    }

    #[test]
    fn an_absent_service_is_told_apart_from_a_refusal() {
        let absent = zbus::Error::FDO(Box::new(zbus::fdo::Error::ServiceUnknown(String::new())));
        assert!(is_service_absent(&absent));

        let unowned = zbus::Error::FDO(Box::new(zbus::fdo::Error::NameHasNoOwner(String::new())));
        assert!(is_service_absent(&unowned));

        let refused = zbus::Error::FDO(Box::new(zbus::fdo::Error::InvalidArgs(
            "no entry 9".to_owned(),
        )));
        assert!(!is_service_absent(&refused));
    }

    /// Hand-written strings drift; asserting them against what zbus itself
    /// produces means a typo in [`ABSENT_SERVICE`] fails here rather than
    /// silently turning a dead daemon into "the daemon refused".
    #[test]
    fn the_absent_service_names_are_the_ones_zbus_produces() {
        use zbus::DBusError as _;

        assert_eq!(
            zbus::fdo::Error::ServiceUnknown(String::new())
                .name()
                .as_str(),
            ABSENT_SERVICE[0]
        );
        assert_eq!(
            zbus::fdo::Error::NameHasNoOwner(String::new())
                .name()
                .as_str(),
            ABSENT_SERVICE[1]
        );
    }

    /// A transport failure is not an error reply and has no name; treating one
    /// as an absent service would blank the applet's list over a hiccup.
    #[test]
    fn an_error_without_a_name_is_not_an_absent_service() {
        let broken = zbus::Error::InputOutput(std::sync::Arc::new(std::io::Error::other("boom")));
        assert_eq!(error_name(&broken), None);
        assert!(!is_service_absent(&broken));
    }
}
