//! The `com.nilfactor.Clippo` D-Bus surface, defined exactly once.
//!
//! Three binaries speak this interface — `clippod` serves it, `clippo` and
//! `clippo-applet` call it — and D-Bus checks signatures at *runtime*. A
//! parameter that drifts from `u` to `x` in one crate and not the others is an
//! `org.freedesktop.DBus.Error.InvalidArgs` at the moment a user clicks
//! something, with nothing at compile time to warn anybody. So neither side
//! restates the signatures:
//!
//! - [`ClippoInterface`] is the served side, `#[zbus::interface]` and all. It
//!   holds no state of its own; it forwards to a [`ClippoBackend`], which is
//!   the trait `clippod` implements.
//! - [`ClippoProxy`] is the calling side, generated by `#[zbus::proxy]` from
//!   the same member list.
//!
//! Changing a signature therefore means changing it here, and every crate that
//! disagrees stops compiling.
//!
//! # The members
//!
//! DESIGN.md's table, verbatim — see `clippod` there:
//!
//! | Member | Signature |
//! |---|---|
//! | `List` | `(limit, offset) -> Vec<EntrySummary>` |
//! | `Search` | `(query, limit) -> Vec<EntrySummary>` |
//! | `Copy` / `Delete` | `(id)` |
//! | `Pin` | `(id, bool)` |
//! | `Clear` | `(include_pinned)` |
//! | `Reveal` | `(id) -> String` |
//! | `SetPaused` / `Paused` | `(bool)` / `-> bool` |
//! | `HistoryChanged` | signal |
//!
//! # Previews and full values
//!
//! [`EntrySummary::preview`] is the *only* content [`List`][ClippoBackend::list]
//! and [`Search`][ClippoBackend::search] return, and
//! [`Reveal`][ClippoBackend::reveal] is the only member that returns a whole
//! stored value. That split is load bearing: M4 makes previews of suspected
//! secrets masked, and it does so by changing the one function that builds a
//! preview. If a full value could leave by any other route, M4 would be a
//! redesign instead of an edit.
//!
//! ```no_run
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let connection = zbus::Connection::session().await?;
//! let clippo = clippo_ipc::ClippoProxy::new(&connection).await?;
//! for entry in clippo.list(10, 0).await? {
//!     println!("{}\t{}", entry.id, entry.preview);
//! }
//! # Ok(())
//! # }
//! ```

mod proxy;
mod service;

use serde::{Deserialize, Serialize};
use zbus::zvariant::Type;

pub use proxy::{ClippoProxy, ClippoProxyBlocking};
pub use service::{emitter, ClippoBackend, ClippoInterface};

/// Well-known bus name of the clippo daemon.
pub const BUS_NAME: &str = "com.nilfactor.Clippo";

/// Object path the daemon exports its interface on.
pub const OBJECT_PATH: &str = "/com/nilfactor/Clippo";

/// Name of the interface itself, which happens to equal [`BUS_NAME`].
///
/// Spelled out separately because the two are different things that are only
/// incidentally the same string: one names a process on the bus, the other
/// names a set of members.
pub const INTERFACE_NAME: &str = "com.nilfactor.Clippo";

/// One history entry as the frontends see it: enough to draw a row, and no
/// clipboard content beyond the preview.
///
/// Deliberately not [`clippo_core::Entry`]. That type carries `hash`, which is
/// an unsalted BLAKE3 of the copied bytes and therefore a confirmation oracle
/// for a guessed value — it belongs inside the encrypted database, not on a
/// session bus that any process running as the user can call. This type is what
/// is safe to hand out.
///
/// The D-Bus signature is `(xxxssbb)`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
pub struct EntrySummary {
    /// The entry's id, as passed back to `Copy`, `Delete`, `Pin` and `Reveal`.
    pub id: i64,
    /// When the copy was first captured, in Unix milliseconds.
    pub created_at: i64,
    /// When it was last copied or pasted, in Unix milliseconds. This is what
    /// [`ClippoBackend::list`] orders by, newest first.
    pub last_used_at: i64,
    /// The [`clippo_core::EntryKind`] word: `text`, `html`, `uris` or `image`.
    pub kind: String,
    /// A short, single-line rendering of the content — `ab••••••••yz` when the
    /// entry is [`sensitive`](Self::sensitive). Never the whole value; that is
    /// `Reveal`'s job alone.
    ///
    /// The masking happened at capture: this field is `entries.preview`, which
    /// is already a mask in the database for a sensitive entry. There is no
    /// unmasked preview anywhere for a `List` or a `Search` to return.
    pub preview: String,
    /// Whether the entry is exempt from retention and from an ordinary
    /// `Clear`.
    pub pinned: bool,
    /// Whether clippo suspects this is a password or a token. Frontends render
    /// a lock badge on these rows.
    pub sensitive: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn object_path_matches_bus_name() {
        assert_eq!(OBJECT_PATH, format!("/{}", BUS_NAME.replace('.', "/")));
    }

    /// The wire signature is what a mismatched frontend actually trips over, so
    /// it is pinned here rather than left to whatever the field order happens
    /// to be after the next edit.
    #[test]
    fn the_entry_summary_signature_is_the_one_frontends_expect() {
        assert_eq!(EntrySummary::SIGNATURE.to_string(), "(xxxssbb)");
    }

    /// `Reveal` returns the whole value; nothing else does. Stated as a test so
    /// that adding a full-value field to this type has to argue with M4 first.
    #[test]
    fn an_entry_summary_carries_no_flavor_data_or_hash() {
        let summary = EntrySummary {
            id: 1,
            created_at: 0,
            last_used_at: 0,
            kind: "text".to_owned(),
            preview: "hu\u{2026}".to_owned(),
            pinned: false,
            sensitive: true,
        };
        let rendered = format!("{summary:?}");
        assert!(!rendered.contains("data"), "{rendered}");
        assert!(!rendered.contains("hash"), "{rendered}");
    }
}
